name: CI Checks
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20
      - name: Downloads
        run: go get -t ./...
      - name: Run Test
        run: go test -v ./...
      - name: Coverage Report
        run: make coverage
      - name: Generate Report
        run: make report
      - name: Copy Files
        run: |
          mkdir reports
          cp cover.html reports/
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: reports
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2
      - name: Build
        run: make build
      - name: Copy files
        run: |
          mkdir artifacts
          cp api artifacts/
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: artifacts
  deliver:
   name: Release
   runs-on: ubuntu-latest
   needs: [build]
   steps:
     - name: Checkout code into the Go module directory
       uses: actions/checkout@v2
     - name: Set up Go 1.x
       uses: actions/setup-go@v2
       with:
         go-version: ^1.20
     - name: Download binary
       uses: actions/download-artifact@v2
       with:
         name: api
         path: artifacts
     - name: CreateRelease
       uses: softprops/action-gh-release@v1
       with:
            files: artifacts/api
            tag_name: ${{ github.ref }}
            body: |
              Release 2 new
            draft: true
            prerelease: true
            token: ${{ secrets.GITHUB_TOKEN }}
  deploy-function:
    name: Deploy Faas
    runs-on: ubuntu-latest
    needs: [test]
    s
